---
title: "Ejercicios"
author: "Uriel Paluch"
date: "1/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
```

## Ejercicio 1
Utilice  el  metodo  de  Newton  para  resolver  el  siguiente  sistema  de  ecuaciones  no  lineales tomando como valores iniciales X(0)=(0.1;0.1) o X(0)=(0.1;0.1;-0.1) segun corresponda. Verificar si la solucion hallada (x1, x2) o (x1, x2, x3) satisface las ecuaciones.


```{r}
# Metodo de Newton --------------------------------------------------------
newton <- function(x, TOL, N = 100, ecuaciones){
  # x: aproximacion inicial
  # TOL: tolerancia
  # N: cantidad maxima de iteraciones
  
  # Instancio las variables -------------------------------------------------
  # n: numero de ecuaciones e incognitas
  n <- length(ecuaciones)
  # funciones valuadas en cero
  f0 <- rep(NA, n)
  jacobiano = matrix(rep(NA, n*n), nrow = n, ncol = n)
  
  # Comienza el metodo ------------------------------------------------------
  for (max_reps in 1:N) {
    # Recorro las filas
    for (i in 1:n) {
      #Evaluo las ecuaciones 
      f0[i] <- eval(ecuaciones[i], x)
      # Recorro las columnas
      for (j in 1:n){
        # Derivo en cada variable y evaluo
        jacobiano[i,j] <- eval((D(ecuaciones[i], glue::glue("x",j))), x)
      }
    }
    
    y0 <- solve(jacobiano) %*% (-f0)
    x <- y0 + unlist(x, use.names=FALSE)
    
    norma <- norm(y0,type = 'M')
    if (norma < TOL) {
      return(x)
    }
    
    x0 <- list()
    for (i in 1:n) {
      x0[glue::glue("x",i)] <- x[i]
    }
    x <- x0
    
  }
  return("Numero de iteraciones maximo excedido")
}
```

### a.
```{r}
# IMPORTANTE: declarar las funciones con x1, x2, ..., xn
print(newton(x = list(x1 = 0.1, x2 = 0.1), TOL = 0.000000001, 
       ecuaciones = c(
                      expression(3*x1^2-x2^2),
                      expression(3*x1*x2^2-x1^3-1)
                      )
))
```

### b.
```{r}
# IMPORTANTE: declarar las funciones con x1, x2, ..., xn
print(newton(x = list(x1 = 0.1, x2 = 0.1, x3 = -0.1), TOL = 0.000000001, 
       ecuaciones = c(
                      expression(3*x1-cos(x2*x3)-0.5),
                      expression(4*x1^2-625*x2^2+2*x2-1),
                      expression(20*x3+(10*pi-3)/3+exp(-x1*x2))
                      )
))
```

### c.
```{r}
# IMPORTANTE: declarar las funciones con x1, x2, ..., xn
print(newton(x = list(x1 = 0.1, x2 = 0.1, x3 = -0.1), TOL = 0.000000001, 
       ecuaciones = c(
                      expression(x1^3+x1^2*x2-x1*x3+6),
                      expression(exp(x1)+exp(x2)-x3),
                      expression(x2^2-2*x1*x3)
                      )
))
```

### d.
```{r}
# IMPORTANTE: declarar las funciones con x1, x2, ..., xn
print(newton(x = list(x1 = 0.1, x2 = 0.1), TOL = 0.000000001, 
       ecuaciones = c(
                      expression(5*x1^2-x2^2),
                      expression(x2-0.25* ( sin(x1) + cos(x2) ) )
                      )
))
```

### e.
```{r}
# IMPORTANTE: declarar las funciones con x1, x2, ..., xn
print(newton(x = list(x1 = 0.1, x2 = 0.1), TOL = 0.000000001, 
       ecuaciones = c(
                      expression(log(x1^2+x2^2)-sin(x1*x2)-log(2)),
                      expression(exp(x1-x2)+cos(x1*x2))
                      )
))
```